version: "3.9"
services:
  h2database:
    build: ./h2database
    volumes:
      - .:/data/clientDB
    ports:
      - 8082:8081
      - 9090:9090

  clientapi:
    build: ./client-service
    ports:
      - 8080:8080
    depends_on: 
      - h2database
